### ISSUE TITLE
msteamsV2 - unhandled exception

### ISSUE THREAD

**Issue by flaviotorres** [walmartlabs/concord-plugins#23]
Hello,

I have setup a public channel named: XX

I've added concord-bot to it

I'm running a test and I'm getting an unhandled exception which I'm not able to understand what's wrong.

Error:

`15:12:09 [ERROR] com.walmartlabs.concord.runner.Main - main -> unhandled exception
java.lang.IllegalArgumentException: No enum constant com.walmartlabs.concord.plugins.msteams.TeamsTaskV2.Action.SENDMESSAGE
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.walmartlabs.concord.plugins.msteams.TeamsTaskV2$Action.valueOf(TeamsTaskV2.java:1)
	at com.walmartlabs.concord.plugins.msteams.TeamsTaskV2.getAction(TeamsTaskV2.java:149)
	at com.walmartlabs.concord.plugins.msteams.TeamsTaskV2.execute(TeamsTaskV2.java:47)
	at com.walmartlabs.concord.runner.TaskCallInterceptor.invoke(TaskCallInterceptor.java:88)
	at com.walmartlabs.concord.runner.engine.EngineFactory$JavaDelegateHandlerImpl.execute(EngineFactory.java:215)
	at io.takari.bpm.reducers.ExpressionsReducer$DelegateFn.call(ExpressionsReducer.java:131)
	at io.takari.bpm.reducers.ExpressionsReducer$DelegateFn.call(ExpressionsReducer.java:1)
	at io.takari.bpm.reducers.ExpressionsReducer.reduce(ExpressionsReducer.java:66)
	at io.takari.bpm.reducers.CombiningReducer.reduce(CombiningReducer.java:18)
	at io.takari.bpm.DefaultExecutor.eval(DefaultExecutor.java:61)
	at io.takari.bpm.AbstractEngine.runLockSafe(AbstractEngine.java:209)
	at io.takari.bpm.AbstractEngine.start(AbstractEngine.java:69)
	at com.walmartlabs.concord.runner.Main.start(Main.java:270)
	at com.walmartlabs.concord.runner.Main.executeProcess(Main.java:170)
	at com.walmartlabs.concord.runner.Main.run(Main.java:142)
	at com.walmartlabs.concord.runner.Main.main(Main.java:484)
15:12:09 [ERROR] Process exit code: 1`

Here's my setup:

Dependency:

`  - mvn://com.walmartlabs.concord.plugins:msteams-task:RELEASE`

```
  - task: msteamsV2
    in:
      action: sendMessage
      webhookUrl: https://outlook.office.com/webhook/............
      title: "Notifications - PRODUCTION ENVIRONMENT"
      text: "Heads up! Some awesome feature is about to be implemented - Change details are :  - Change record ID is: "
      ignoreErrors: true

  - if: "${!result.ok}"
    then:
      - throw: "Error while sending a message: ${result.error}"
    else:
      - log: "Data: ${result.data}"
```
