### ISSUE TITLE
Terraform versioning

### ISSUE THREAD

**Issue by mgobec** [walmartlabs/concord-plugins#4]
Currently, terraform plugin version includes a specific terraform binary with a version hardcoded in pom.xml. If we are to use a different terraform version, like 0.12, is there a way to specify a binary dependency other than through pom file? What are the options?

I'm thinking about an approach that uses concord flow and a terraform plugin variable to specify a binary version like:

```
# run terraform plan in ${workDir}
- task: terraform
  version: 0.12.3
  in:
    action: plan
```

Do you see any side effects of such an approach?
