### ISSUE TITLE
terraform: NoSuchFileException in ConcordV1Backend

### ISSUE THREAD

**Issue by ibodrov** [walmartlabs/concord-plugins#40]
When using `runtime-v1` running

```
- task: terraform
  in:
   action: plan
   dir: somedir
```

results in `java.nio.file.NoSuchFileException: /tmp/concord/prefork17606539003391389201/payload/somedir/concord_override.tf.json` if `somedir` doesn't exist.

The plugin must produce a better error message.
