### ISSUE TITLE
confluence-task: support for workflow default variable

### ISSUE THREAD

**Issue by benbroadaway** [walmartlabs/concord-plugins#71]
Currently, the runtime-v2 `confluence` plugin does not support workflow-defined default variables like the [documentation suggests](https://concord.walmart.com/docs/plugins/confluence.html#overview).

```yaml
configuration:
  arguments:
    confluenceParams:
      apiUrl: "https://confluence.example.com/rest/api/"
```

It _does_ support policy-defined default variables, but a user can't use a "global" workflow variable defined in `configuration.arguments` to override the defaults.

https://github.com/walmartlabs/concord-plugins/blob/1dd5cae1bd80b4020c335b678903fed9c0aef362/tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/v2/ConfluenceTaskV2.java#L46-L47

For parity with the runtime-v1 task implementation, it should look for a similar default global variable and let it override the policy-defined default.
