### ISSUE TITLE
terraform-task: planPath value is incorrect when working in sub-directory

### ISSUE THREAD

**Issue by benbroadaway** [walmartlabs/concord-plugins#88]
The plugin prints the correct path, but the value in the returned `planPath` value is incorrect. For example, the plugin prints the terraform output showing where the plan file is saved
```text
Saved the plan to: /tmp/concord/workDir1115761774917567127/compute/env/my_env/_attachments/terraform/tf92403a96-0e55-473b-a4a6-15ea0513d5af.plan
```

But the actual (incorrect) value set in the process is
```
"/tmp/concord/workDir1115761774917567127/_attachments/terraform/tf92403a96-0e55-473b-a4a6-15ea0513d5af.plan"
```

example task parameters to re-create the issue
```yaml
- task: terraform
  in:
    action: plan
    pwd: "some/sub/dir"
    backend: "concord"
    toolUrl: "https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip"
    stateId: "my-env-tf-state"
  out: result
```
